### ISSUE TITLE
If a Solution was deleted in CRM but exists still local an error will occure

### ISSUE THREAD

**Issue by jhueppauff-itvt** [jhueppauff/Dynamics365-Customizing-Downloader#63]
An error occured while retriving the CRM Solutions : Object reference not set to an instance of an object.
 at Dynamics365CustomizingDownloader.Pages.SolutionSelector.Worker_DoWork(Object sender, DoWorkEventArgs e) in d:\a\1\s\Dynamics365 Customizing Downloader\Pages\SolutionSelector.xaml.cs:line 113
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by jhueppauff-itvt** [comment]
issue still persists
